---
title: "R Notebook"
output: html_notebook
---
```{r}

w_dir<-"C:/Users/zacha/Desktop/IMAP_Work_Loos/HourlyWeather/"
### load in columns and subset columns
colsforHR<-c("WBanno","UTC_Date","UTCTime","LST_Date","LST_Time",
            "CRX_VN","LONG","LAT","T_Calc","T_HR_AVG","T_Max","T_Min")
years<-c(2007,2008,2009,2010,2011,2012)
TrunDF<-NULL
for(i in years){
  HourlyYr1<-read.delim(paste0(w_dir,"CRNH0203-",i,"-CA_Yosemite_Village_12_W.txt"),header=F,stringsAsFactors = F,sep="")
  colnames(HourlyYr1)[1:12]<-colsforHR
  TrunHourly<-HourlyYr1[1:12]
  TrunDF<-rbind(TrunDF,TrunHourly)
}



TrunHourly<-TrunDF
```

```{r}

### Removing out nas and aggrgating 
TR_Daily_Max<-aggregate(list(DailyMax=TrunHourly$T_Max[TrunHourly$T_Max>-9999]),by=list(Date=TrunHourly$LST_Date[TrunHourly$T_Max>-9999]),FUN=max)
## Make dataframe for hourly 
TR_Hourly_Max<-data.frame(Date=TrunHourly$LST_Date,Hour=TrunHourly$UTCTime, Hourly=TrunHourly$T_Max)
### Merge together to keep index continouinty 
TR_Together_Max<-merge(TR_Daily_Max,TR_Hourly_Max)
TR_Together_Max$Date<-as.Date(as.character(TR_Together_Max$Date), format="%Y%m%d")
TR_Together_Max<-TR_Together_Max[TR_Together_Max$Date>"2007-10-01",]

## Number of Hours missing data. 
length(TrunHourly$T_Max)-length(TrunHourly$T_Max[TrunHourly$T_Max>-9999])
## Replace average with daily mean. 
TR_Together_Max$Hourly[TR_Together_Max$Hourly==-9999]<-TR_Together_Max$DailyMax[TR_Together_Max$Hourly==-9999]

plot(TR_Together_Max$Hourly[TR_Together_Max$Hourly>-9999],ylab="Degrees C",ylim=c(-15,50))
points(TR_Together_Max$DailyMax[TR_Together_Max$Hourly>-99],col="red")
legend(0,50,legend=c("Daily Max","Hourly Max"),col=c("red","black"),pch=c(1,1))

### Removing out nas and aggrgating 
TR_Daily_Min<-aggregate(list(DailyMin=TrunHourly$T_Min[TrunHourly$T_Min>-9999]),by=list(Date=TrunHourly$LST_Date[TrunHourly$T_Min>-9999]),FUN=min)
## Make dataframe for hourly 
TR_Hourly_Min<-data.frame(Date=TrunHourly$LST_Date,Hour=TrunHourly$UTCTime, Hourly=TrunHourly$T_Min)
### Merge together to keep index continouinty 
TR_Together_Min<-merge(TR_Daily_Min,TR_Hourly_Min)
TR_Together_Min$Date<-as.Date(as.character(TR_Together_Min$Date), format="%Y%m%d")
TR_Together_Min<-TR_Together_Min[TR_Together_Min$Date>"2007-10-01",]

## Number of Hours missing data. 
length(TrunHourly$T_Min)-length(TrunHourly$T_Min[TrunHourly$T_Min>-9999])
## Replace average with daily mean. 
TR_Together_Min$Hourly[TR_Together_Min$Hourly==-9999]<-TR_Together_Min$DailyMin[TR_Together_Min$Hourly==-9999]

plot(TR_Together_Min$Hourly[TR_Together_Min$Hourly>-9999])
points(TR_Together_Min$DailyMin[TR_Together_Min$Hourly>-99],col="red")

legend(0,50,legend=c("Daily Min","Hourly Min"),col=c("red","black"),pch=c(1,1))
```



```{r}
#oviposition
sigma0 = 0.2458         # controls rate variability
TB0 = 7.750          #base temperature in degrees C
DeltaB0 = 10000
TM0 = 34.887           #max temperature in degree C
DeltaM0 = 2.0
omega0 = .0085
psi0 = 0.013

#parameters for development rate for eggs
sigma1=.3     
Rmax1=0.187          
Tmax1=34.741
Tmin1= 7.267
k1= 1056.233
dm1 = 7.588


# parameters for development rate for larvae
sigma2=.3     
Rmax2=.038            
VTmx2=34.701
VTmn2= 5.167
k2= 766.410
dm2 = 7.566

# parameters for development rate for Prepupae
sigma3=.3     
Rmax3=0.231          
VTmx3=37.599
VTmn3= 4.30
k3= 431.000
dm3 = 11.30

# parameters for development rate for Pupae
sigma4=.3     
Rmax4=.062        
VTmx4=31.528
VTmn4= 5.840
k4= 203.096
dm4 = 10.016

# parameters for development rate for TA
sigma5=.3     
Rmax5=.01568408 
VTmx5=50.8
VTmn5= -0.002603655
k5= -0.003262513
dm5 = 0.0005461579
LoganFunc<-function(Temp,Rmax,Tmax,Tmin,k,dm,DevR){
  DevR =Rmax*(((((Temp-Tmin)**2)/(((Temp-Tmin)**2)+k))-(exp(-(Tmax-(Temp-Tmin))/dm))))
  return(DevR)
}
RegniereFunc<-function(TC,TB,DeltaB,TM,DeltaM,omega,psi){
  Fec1= psi*(exp(omega*(TC - TB)) - (TM - TC)/(TM - TB)*exp(-omega*(TC - TB)/DeltaB) - (TC - TB)/(TM - TB)*exp(omega*(TM - TB) - (TM - TC)/DeltaM))
 return(Fec1) 
}

```


```{r}
plot(Tempmind)
```

```{r}


#Tempmind<-
Tempmind<-TR_Together_Min$DailyMin[!duplicated(TR_Together_Min$Date)]
Tempmaxd<-TR_Together_Max$DailyMax[!duplicated(TR_Together_Max$Date)]
#Tempmaxd<-Tempmaxd
DatesD<-TR_Together_Max$Date[!duplicated(TR_Together_Max$Date)]



Fec=0
Egg=0
L1<-0
L2<-0
P<-0
TA<-0
Gen<-0
time<-0
Flycount=0
df<-NULL


### For i 
time<-0
#length(Tempmind)
for(i in 1:(length(Tempmind)-1)){
time=time+1
Tmaxstep=DatesD
Tmintime=Tempmind[i]
TminNext=Tempmind[i+1]
TmaxTime=Tempmaxd[i]

CMean=(TmaxTime+Tmintime)/2
CMean2=(TmaxTime+TminNext)/2
CDif=(TmaxTime-Tmintime)
CDif2=(TmaxTime-TminNext)
fouram=3.8532+(Tmintime*.9677)
Tmin2=fouram
sevenam=1.86978+(.93522*(CMean+(.5*CDif*-0.7071068)))
tenam=(-.4533)+(1.00899*(CMean))
onepm=(-1.148846)+(.985801*(CMean+(.5*CDif*0.7071068)))
fourpm=(.0656866)+(.942395*(CMean+(.5*CDif*1)))
sevenpm=(-0.702683)+(.979172*(CMean2+(.5*CDif2*0.7071068)))
tenpm=.934665+(.988126*(CMean2))
oneam=3.2294+(.9842*(CMean2+(.5*CDif2*-0.7071068)))
Tmax2=fourpm



#print(time)
if(Fec<1){
  med0t1<- RegniereFunc(fouram, TB0, DeltaB0, TM0, DeltaM0, omega0, psi0)   # for pre-eggs
  med0t2<- RegniereFunc(sevenam, TB0, DeltaB0, TM0, DeltaM0, omega0, psi0)   # for pre-eggs
  med0t3<- RegniereFunc(tenam, TB0, DeltaB0, TM0, DeltaM0, omega0, psi0)   # for pre-eggs
	med0t4<- RegniereFunc(onepm, TB0, DeltaB0, TM0, DeltaM0, omega0, psi0)   # for pre-eggs
	med0t5<- RegniereFunc(fourpm, TB0, DeltaB0, TM0, DeltaM0, omega0, psi0)   # for pre-eggs
	med0t6<- RegniereFunc(sevenpm, TB0, DeltaB0, TM0, DeltaM0, omega0, psi0)   # for pre-eggs
	med0t7<- RegniereFunc(tenpm, TB0, DeltaB0, TM0, DeltaM0, omega0, psi0)   # for pre-eggs
	med0t8<- RegniereFunc(oneam, TB0, DeltaB0, TM0, DeltaM0, omega0, psi0)   # for pre-eggs
  Fec1=med0t1+med0t2+med0t3+med0t4+med0t5+med0t6+med0t7+med0t8
	
  if(Fec1<0){Fec1=0}
  
  Fec=(Fec1)+Fec
  if(Fec>1.0){
  Egg=Fec-1.0
  Fec=1.0
  if(Egg >.90){Egg=.90}
  }

}

### Need to remove the a's and i's in max

###Egg
if(Fec==1.0&Egg<1){
  med1t1<-LoganFunc(fouram, Rmax1,Tmax1,Tmin1,k1,dm1)
  med1t2<-LoganFunc(sevenam, Rmax1,Tmax1,Tmin1,k1,dm1)
  med1t3<-LoganFunc(tenam, Rmax1,Tmax1,Tmin1,k1,dm1)
  med1t4<-LoganFunc(onepm, Rmax1,Tmax1,Tmin1,k1,dm1)
  med1t5<-LoganFunc(fourpm, Rmax1,Tmax1,Tmin1,k1,dm1)
  med1t6<-LoganFunc(sevenpm, Rmax1,Tmax1,Tmin1,k1,dm1)
  med1t7<-LoganFunc(tenpm, Rmax1,Tmax1,Tmin1,k1,dm1)
  med1t8<-LoganFunc(oneam, Rmax1,Tmax1,Tmin1,k1,dm1)
  Rate=med1t1+med1t2+med1t3+med1t4+med1t5+med1t6+med1t7+med1t8
  if(Rate<0){Rate=0}
  Egg=Egg+Rate
  if(Egg>1.0){
    L1=Egg-1.0
    if(L1 >.90){L1=.90}
    Egg=1.0
  }
}

###Larval

if(L1<1 &Egg==1 & Fec==1){
  med2t1<-LoganFunc(fouram, Rmax2,VTmx2,VTmn2,k2,dm2)
  med2t2<-LoganFunc(sevenam, Rmax2,VTmx2,VTmn2,k2,dm2)
  med2t3<-LoganFunc(tenam, Rmax2,VTmx2,VTmn2,k2,dm2)
  med2t4<-LoganFunc(onepm, Rmax2,VTmx2,VTmn2,k2,dm2)
  med2t5<-LoganFunc(fourpm, Rmax2,VTmx2,VTmn2,k2,dm2)
  med2t6<-LoganFunc(sevenpm, Rmax2,VTmx2,VTmn2,k2,dm2)
  med2t7<-LoganFunc(tenpm, Rmax2,VTmx2,VTmn2,k2,dm2)
  med2t8<-LoganFunc(oneam, Rmax2,VTmx2,VTmn2,k2,dm2)
  Rate=med2t1+med2t2+med2t3+med2t4+med2t5+med2t6+med2t7+med2t8
if(Rate<0){Rate=0}
      L1<-L1+Rate
      if(L1>1.0){
        L2=L1-1.0
        L1=1.0}
  }
### Pre-Pupal

 if(L2<1 & L1==1 &Egg==1 & Fec==1){
  med3t1<-LoganFunc(fouram, Rmax3,VTmx3,VTmn3,k3,dm3)
  med3t2<-LoganFunc(sevenam, Rmax3,VTmx3,VTmn3,k3,dm3)
  med3t3<-LoganFunc(tenam, Rmax3,VTmx3,VTmn3,k3,dm3)
  med3t4<-LoganFunc(onepm, Rmax3,VTmx3,VTmn3,k3,dm3)
  med3t5<-LoganFunc(fourpm, Rmax3,VTmx3,VTmn3,k3,dm3)
  med3t6<-LoganFunc(sevenpm, Rmax3,VTmx3,VTmn3,k3,dm3)
  med3t7<-LoganFunc(tenpm, Rmax3,VTmx3,VTmn3,k3,dm3)
  med3t8<-LoganFunc(oneam, Rmax3,VTmx3,VTmn3,k3,dm3)
  Rate=med3t1+med3t2+med3t3+med3t4+med3t5+med3t6+med3t7+med3t8
      if(fouram<12.8){Rate=0}
      if(Rate<0){Rate=0}
      L2<-L2+Rate
      if(L2>1.0){
        P=L2-1.0
        L2=1.0}
    }

if(P<1 &L2==1 & L1==1 &Egg ==1 & Fec==1){
    med4t1<-LoganFunc(fouram, Rmax4,VTmx4,VTmn4,k4,dm4)
    med4t2<-LoganFunc(sevenam, Rmax4,VTmx4,VTmn4,k4,dm4)
    med4t3<-LoganFunc(tenam, Rmax4,VTmx4,VTmn4,k4,dm4)
    med4t4<-LoganFunc(onepm, Rmax4,VTmx4,VTmn4,k4,dm4)
    med4t5<-LoganFunc(fourpm, Rmax4,VTmx4,VTmn4,k4,dm4)
    med4t6<-LoganFunc(sevenpm, Rmax4,VTmx4,VTmn4,k4,dm4)
    med4t7<-LoganFunc(tenpm, Rmax4,VTmx4,VTmn4,k4,dm4)
    med4t8<-LoganFunc(oneam, Rmax4,VTmx4,VTmn4,k4,dm4)
    Rate=med4t1+med4t2+med4t3+med4t4+med4t5+med4t6+med4t7+med4t8
      if(Rate<0){Rate=0}
      P<-P+Rate
      if(P>1.0){
        TA=P-1.0
        P=1.0}
    }

if(TA<1 &P==1 &L2==1 & L1==1 &Egg ==1 & Fec==1){
    med5t1<-LoganFunc(fouram, Rmax5,VTmx5,VTmn5,k5,dm5)
    med5t2<-LoganFunc(sevenam, Rmax5,VTmx5,VTmn5,k5,dm5)
    med5t3<-LoganFunc(tenam, Rmax5,VTmx5,VTmn5,k5,dm5)
    med5t4<-LoganFunc(onepm, Rmax5,VTmx5,VTmn5,k5,dm5)
    med5t5<-LoganFunc(fourpm, Rmax5,VTmx5,VTmn5,k5,dm5)
    med5t6<-LoganFunc(sevenpm, Rmax5,VTmx5,VTmn5,k5,dm5)
    med5t7<-LoganFunc(tenpm, Rmax5,VTmx5,VTmn5,k5,dm5)
    med5t8<-LoganFunc(oneam, Rmax5,VTmx5,VTmn5,k5,dm5)
    Rate=med5t1+med5t2+med5t3+med5t4+med5t5+med5t6+med5t7+med5t8
      if(Rate<0){Rate=0}
      TA<-TA+Rate
      if(TA>=1.0){TA=1.0}
    } 
if(TA==1 &P==1 &L2==1 & L1==1 &Egg ==1 & Fec==1 & Tempmaxd[i] >18.6 & Tempmaxd[i]<=38.9){
      Flycount=Flycount+1
      if(Flycount==1){
        Fec=0
        Egg=0
        L1<-0
        L2<-0
        P<-0
        TA<-0
        Gen<-Gen+1
        Flycount=0
      }
    }
    
    row<-cbind(time,Fec,Egg,L1,L2,P,TA,Gen)  
    df<-rbind(row,df)
  }
 # return(df[order(df[,1],decreasing = F),])
#}    

```


```{r,fig.width=10.0}


df<-df[order(df[,1],decreasing = F),]
Progression_Daily<-rowSums(df[,c(2:7)])

#Dates
plot(DatesD[1:1917],Progression_Daily,yaxt='n',xlab=NA,
     ylab=NA,type="l",col="red",cex.axis=2.0,lwd=5.,main="Northern Low Elevation",cex.main=4.0)


length(DatesD)
length(Progression)

plot(DatesD,Tempmaxd)
```




### Daily

```{r}
TR_Daily<-aggregate(list(DailyMean=TrunHourly$T_HR_AVG[TrunHourly$T_HR_AVG>-9999]),by=list(Date=TrunHourly$LST_Date[TrunHourly$T_HR_AVG>-9999]),FUN=mean)
TR_Hourly<-data.frame(Date=TrunHourly$LST_Date,Hour=TrunHourly$UTCTime, Hourly=TrunHourly$T_HR_AVG)

TR_Together<-merge(TR_Daily,TR_Hourly)
TR_Together$Date<-as.Date(as.character(TR_Together$Date), format="%Y%m%d")
## Number of Hours missing data. 
length(TrunHourly$T_HR_AVG)-length(TrunHourly$T_HR_AVG[TrunHourly$T_HR_AVG>-9999])
## Replace average with daily mean. 
TR_Together$Hourly[TR_Together$Hourly==-9999]<-TR_Together$DailyMean[TR_Together$Hourly==-9999]

plot(TR_Together$Hourly[TR_Together$Hourly>-9999])
points(TR_Together$DailyMean[TR_Together$Hourly>-99],col="red")

TempinH_frame<-data.frame(Date=TR_Together$Date,Hourly=TR_Together$Hourly,Hour=TR_Hourly$Hour)

Fec=0
Egg=0
L1<-0
L2<-0
P<-0
TA<-0
Gen<-0
time<-0
Flycount=0
df<-NULL
hour<-20

### For i 
time<-0
#length(Tempmind)
for(i in 1:(length(TempinH_frame$Hourly)-1)){
time=time+1
#print(i)
TempinH<-TempinH_frame$Hourly[i]

if(hour>=0 & hour <= 2){fouram=3.2294+(TempinH)}
if(hour>=3 & hour <= 5){fouram=3.8532+(TempinH*.9677)}
if(hour>=6 & hour <= 8){fouram=1.86978+(.93522*(TempinH))}
if(hour>=9 & hour <= 11){fouram=(-.4533)+(1.00899*(TempinH))}
if(hour>=12 & hour <= 14){fouram=(-1.148846)+(.985801*(TempinH))}
if(hour>=15 & hour <= 17){fouram=(.0656866)+(.942395*(TempinH))}
if(hour>=18 & hour <= 20){fouram=(-0.702683)+(TempinH)}
if(hour>=21 & hour <= 23){fouram=.934665+(.988126*TempinH)}
if(hour==23){hour<-0}



#print(time)
if(Fec<1){
  med0t1<- RegniereFunc(fouram, TB0, DeltaB0, TM0, DeltaM0, omega0, (psi0/3))   # for pre-eggs

  Fec1=med0t1
	
  if(Fec1<0){Fec1=0}
  
  Fec=(Fec1)+Fec
  if(Fec>1.0){
  Egg=Fec-1.0
  Fec=1.0
  if(Egg >.90){Egg=.90}
  }

}

### Need to remove the a's and i's in max

###Egg
if(Fec==1.0&Egg<1){
  med1t1<-LoganFunc(fouram, (Rmax1/3),Tmax1,Tmin1,k1,dm1)

  Rate=med1t1
  if(Rate<0){Rate=0}
  Egg=Egg+Rate
  if(Egg>1.0){
    L1=Egg-1.0
    if(L1 >.90){L1=.90}
    Egg=1.0
  }
}

###Larval

if(L1<1 &Egg==1 & Fec==1){
  med2t1<-LoganFunc(fouram, (Rmax2/3),VTmx2,VTmn2,k2,dm2)

  Rate=med2t1
if(Rate<0){Rate=0}
      L1<-L1+Rate
      if(L1>1.0){
        L2=L1-1.0
        L1=1.0}
  }
### Pre-Pupal

 if(L2<1 & L1==1 &Egg==1 & Fec==1){
  med3t1<-LoganFunc(fouram,(Rmax3/3),VTmx3,VTmn3,k3,dm3)
  Rate=med3t1
      if(fouram<12.8){Rate=0}
      if(Rate<0){Rate=0}
      L2<-L2+Rate
      if(L2>1.0){
        P=L2-1.0
        L2=1.0}
    }

if(P<1 &L2==1 & L1==1 &Egg ==1 & Fec==1){
    med4t1<-LoganFunc(fouram, (Rmax4/3),VTmx4,VTmn4,k4,dm4)
  
    Rate=med4t1
      if(Rate<0){Rate=0}
      P<-P+Rate
      if(P>1.0){
        TA=P-1.0
        P=1.0}
    }

if(TA<1 &P==1 &L2==1 & L1==1 &Egg ==1 & Fec==1){
    med5t1<-LoganFunc(fouram, (Rmax5/3),VTmx5,VTmn5,k5,dm5)
    Rate=med5t1
      if(Rate<0){Rate=0}
      TA<-TA+Rate
      if(TA>=1.0){TA=1.0}
    } 
if(TA==1 &P==1 &L2==1 & L1==1 &Egg ==1 & Fec==1 & fouram >18.6 & fouram <=38.9){
      Flycount=Flycount+1
      if(Flycount==1){
        Fec=0
        Egg=0
        L1<-0
        L2<-0
        P<-0
        TA<-0
        Gen<-Gen+1
        Flycount=0
      }
    }
    
    row<-cbind(time,Fec,Egg,L1,L2,P,TA,Gen)  
    df<-rbind(row,df)
  }
```

```{r,fig.width=10.0}
df_Hourly<-df[order(df[,1],decreasing = F),]
Progression_Hourly<-rowSums(df_Hourly[,c(2:7)])
length(TR_Together$Date)
length(Progression)
plot(TR_Together$Date[1:46108],Progression,yaxt='n',xaxt="n",xlab=NA,
     ylab=NA,type="l",col="red",cex.axis=2.0,lwd=5.,main="Northern Low Elevation",cex.main=4.0)
lines(DatesD[1:1917],Progression_Daily,col="blue",lwd=5.0)
```




```{r}
GenerationsHourly<-df_Hourly[,8]+(Progression_Hourly/8)
GenerationsDaily<-df[,8]+(Progression_Daily/8)
plot(DatesD[1:1917],Generations,xaxt="n",xlab=NA,
     ylab=NA,type="l",col="red",cex.axis=2.0,lwd=5.,main="Northern Low Elevation",cex.main=4.0)
lines(TR_Together$Date[1:46108],GenerationsHourly)
```

