---
title: "Phi"
author: "Zjrobbin"
date: "2/11/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r,fig.height=5.0,fig.width=10.0}
Phi<-exp(10.03+(1.545*SPI)+.505)
plot(SPI,Phi)


SPI<-seq(-3,1,.1)
Phi<-exp(10.03+(1.545*SPI)+.505)
Phi2<-exp(10.03+(1.545*SPI))
max(Phi)
SPI<-seq(-3,1.0,.1)
Phi<-exp(10.03+(1.545*SPI)+.505)
Phi2<-exp(10.03+(1.545*SPI))
dev.off()
par(mfrow=c(1,2))

plot(SPI,Phi,pch=19,col="orange",main="a) Phi in relation to SPI 4 year lag",
     cex=1.2,cex.lab=1.2,cex.axis=1.2)
points(SPI,Phi2,pch=19,col="purple")
legend(-3,100000,legend=c("Phi for trees 10-31.8cm","Phi for trees >31.8cm"),
       box.col = "white",bg = "white",pch=c(19,19),col=c("purple","orange"))
plot(SPI,Phi,ylim=c(0,10000),col="orange",pch=19,main="b) Phi~SPI for ranges less than 10,000",cex=1.2,cex.lab=1.2,cex.axis=1.2)
points(SPI,Phi2,ylim=c(0,10000),col="purple",pch=19)
legend(-1.3,2000,legend=c("Phi for trees 10-31.8cm","Phi for trees >31.8cm"),
       box.col = "white",bg = "white",pch=c(19,19),col=c("purple","orange"))

```

```{r,fig.height=10.0,fig.width=10.0}
SPI_4<-read.csv("C:/Users/zacha/Documents/GitHub/IMAP_Python_Project/WPB_Model/WPB_Inputs/WPB_SPI_620.csv")
MeanLS<-rowMeans(SPI_4[,c(3:6)])

exp(10.03+(1.545*max(MeanLS)))


par(mfrow=c(2,1))
plot(as.Date(SPI_4$Dates),exp(10.03+(1.545*MeanLS)+.505),type="l",col="purple",
     ylab=expression(phi),xlab="Date",main=expression(paste("A) ",phi," through simulation")),cex=1.2,cex.lab=1.2,cex.axis=1.2)
lines(as.Date(SPI_4$Dates),exp(10.03+(1.545*MeanLS)),lty=1,col="orange")
legend(as.Date(SPI_4$Dates)[3000],100000,legend=c(expression(paste(phi," for trees 10-31.8cm")) ,expression(paste(phi," for trees >31.8cm"))),
       box.col = "white",bg = "white",lty=c(1,1),col=c("purple","orange"))

plot(as.Date(SPI_4$Dates),exp(10.03+(1.545*MeanLS)+.505),
     type="l",col="purple",ylim=c(0,15000),ylab=expression(phi),xlab="Date",
     main=expression(paste("B) ",phi," through simulation, values less than 15,000")),cex=1.2,cex.lab=1.2,cex.axis=1.2)
lines(as.Date(SPI_4$Dates),exp(10.03+(1.545*MeanLS)),lty=1,col="orange")
legend(as.Date(SPI_4$Dates)[1500],3000,legend=c(expression(paste(phi," for trees 10-31.8cm")),expression(paste(phi," for trees >31.8cm"))),
       box.col = "white",bg = "white",lty=c(1,1),col=c("purple","orange"))
```

